import type { CardDef } from './types.ts';

// Card definitions with copy counts and minimum player thresholds.
// The "copies" field is how many copies exist in the full 108-card deck.
// minPlayers: only include if playerCount >= this value.

export const CARD_DEFS: CardDef[] = [
  // ── Infections ────────────────────────────────────────────────────────
  {
    id: 'the_thing',
    name: 'The Thing',
    nameRu: 'Нечто',
    category: 'infection',
    back: 'event',
    description: 'You ARE The Thing. Cannot be discarded or traded.',
    descriptionRu: 'Вы — Нечто. Нельзя сбросить или обменять.',
    copies: 1,
    minPlayers: 4,
  },
  {
    id: 'infected',
    name: 'Infected!',
    nameRu: 'Заражение!',
    category: 'infection',
    back: 'event',
    description: 'Passed by The Thing during trade to infect a player.',
    descriptionRu: 'Передаётся Нечто при обмене для заражения игрока.',
    copies: 8,
    minPlayers: 4,
  },

  // ── Actions ───────────────────────────────────────────────────────────
  {
    id: 'flamethrower',
    name: 'Flamethrower',
    nameRu: 'Огнемёт',
    category: 'action',
    back: 'event',
    description: 'Eliminate an adjacent player. Blocked by "No Barbecue!"',
    descriptionRu: 'Уничтожить соседнего игрока. Блокируется «Никакого шашлыка!»',
    copies: 5,
    minPlayers: 4,
  },
  {
    id: 'analysis',
    name: 'Analysis',
    nameRu: 'Анализ',
    category: 'action',
    back: 'event',
    description: 'Target adjacent player shows you ALL their hand cards.',
    descriptionRu: 'Соседний игрок показывает вам ВСЕ свои карты.',
    copies: 4,
    minPlayers: 4,
  },
  {
    id: 'axe',
    name: 'Axe',
    nameRu: 'Топор',
    category: 'action',
    back: 'event',
    description: 'Remove a Quarantine card or a Locked Door between you and an adjacent player.',
    descriptionRu: 'Убрать карантин или заблокированную дверь между вами и соседом.',
    copies: 4,
    minPlayers: 4,
  },
  {
    id: 'suspicion',
    name: 'Suspicion',
    nameRu: 'Подозрение',
    category: 'action',
    back: 'event',
    description: 'Take 1 random card from adjacent player, look secretly, return it.',
    descriptionRu: 'Возьмите 1 случайную карту соседа, посмотрите тайно, верните.',
    copies: 6,
    minPlayers: 4,
  },
  {
    id: 'whisky',
    name: 'Whisky',
    nameRu: 'Виски',
    category: 'action',
    back: 'event',
    description: 'Show ALL your cards to all players.',
    descriptionRu: 'Покажите ВСЕ свои карты всем игрокам.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'persistence',
    name: 'Persistence',
    nameRu: 'Упорство',
    category: 'action',
    back: 'event',
    description: 'Draw 3 event cards, keep 1, discard 2. Then play or discard 1 card.',
    descriptionRu: 'Возьмите 3 карты событий, оставьте 1, сбросьте 2. Затем сыграйте или сбросьте ещё 1 карту.',
    copies: 4,
    minPlayers: 4,
  },
  {
    id: 'watch_your_back',
    name: 'Watch Your Back!',
    nameRu: 'Оглянись!',
    category: 'action',
    back: 'event',
    description: 'Reverse the turn direction.',
    descriptionRu: 'Изменить направление хода.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'swap_places',
    name: 'Swap Places!',
    nameRu: 'Меняемся местами!',
    category: 'action',
    back: 'event',
    description: 'Swap seats with an adjacent player (not in quarantine, not behind locked door).',
    descriptionRu: 'Поменяться местами с соседом (не на карантине, не за заблокированной дверью).',
    copies: 5,
    minPlayers: 4,
  },
  {
    id: 'get_out_of_here',
    name: 'Get Out of Here!',
    nameRu: 'Убирайся отсюда!',
    category: 'action',
    back: 'event',
    description: 'Swap seats with ANY player (not in quarantine; locked doors ignored).',
    descriptionRu: 'Поменяться местами с ЛЮБЫМ игроком (не на карантине; двери игнорируются).',
    copies: 4,
    minPlayers: 4,
  },
  {
    id: 'temptation',
    name: 'Temptation',
    nameRu: 'Соблазн',
    category: 'action',
    back: 'event',
    description: 'Swap 1 card with ANY player (not in quarantine). This ends your trade step.',
    descriptionRu: 'Обменяться 1 картой с ЛЮБЫМ игроком (не на карантине). Обмен завершается.',
    copies: 4,
    minPlayers: 4,
  },

  // ── Defense ───────────────────────────────────────────────────────────
  {
    id: 'fear',
    name: 'Fear',
    nameRu: 'Страх',
    category: 'defense',
    back: 'event',
    description: 'Refuse trade. Secretly look at the offered card, return it.',
    descriptionRu: 'Отказ от обмена. Тайно посмотрите предложенную карту и верните.',
    copies: 4,
    minPlayers: 4,
  },
  {
    id: 'no_thanks',
    name: 'No Thanks!',
    nameRu: 'Нет, спасибо!',
    category: 'defense',
    back: 'event',
    description: 'Refuse trade.',
    descriptionRu: 'Отказ от обмена.',
    copies: 4,
    minPlayers: 4,
  },
  {
    id: 'miss',
    name: 'Miss!',
    nameRu: 'Мимо!',
    category: 'defense',
    back: 'event',
    description: 'Refuse trade, but the next player in turn order trades instead.',
    descriptionRu: 'Отказ от обмена, но следующий по ходу игрок обменивается вместо вас.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'im_fine_here',
    name: "I'm Fine Here",
    nameRu: 'Мне и тут хорошо',
    category: 'defense',
    back: 'event',
    description: 'Cancel "Swap Places!" or "Get Out of Here!"',
    descriptionRu: 'Отменить «Меняемся местами!» или «Убирайся отсюда!»',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'no_barbecue',
    name: 'No Barbecue!',
    nameRu: 'Никакого шашлыка!',
    category: 'defense',
    back: 'event',
    description: 'Cancel Flamethrower. Stay in the game.',
    descriptionRu: 'Отменить Огнемёт. Остаться в игре.',
    copies: 3,
    minPlayers: 4,
  },

  // ── Obstacles ─────────────────────────────────────────────────────────
  {
    id: 'quarantine',
    name: 'Quarantine',
    nameRu: 'Карантин',
    category: 'obstacle',
    back: 'event',
    description: 'Target cannot trade, play events, or be targeted for 3 turns.',
    descriptionRu: 'Цель не может обменивать, играть события или быть целью 3 хода.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'locked_door',
    name: 'Locked Door',
    nameRu: 'Запертая дверь',
    category: 'obstacle',
    back: 'event',
    description: 'Place between you and neighbor. Neither can target each other.',
    descriptionRu: 'Поставить между вами и соседом. Никто не может действовать друг на друга.',
    copies: 3,
    minPlayers: 4,
  },

  // ── Panic cards ───────────────────────────────────────────────────────
  {
    id: 'panic_1234',
    name: 'One, Two... Three, Four...',
    nameRu: 'Раз, два... три, четыре...',
    category: 'panic',
    back: 'panic',
    description: 'Next 3 players swap seats with their neighbor in turn direction.',
    descriptionRu: 'Следующие 3 игрока меняются местами с соседом по направлению хода.',
    copies: 2,
    minPlayers: 4,
  },
  {
    id: 'panic_party',
    name: 'Is This What You Call a Party?',
    nameRu: 'И это вы называете вечеринкой?',
    category: 'panic',
    back: 'panic',
    description: 'All players pass 1 card to their neighbor in turn direction.',
    descriptionRu: 'Все игроки передают 1 карту соседу по направлению хода.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'panic_between_us',
    name: 'Just Between Us',
    nameRu: 'Только между нами',
    category: 'panic',
    back: 'panic',
    description: 'Pick two adjacent players; they must trade 1 card.',
    descriptionRu: 'Выберите двух соседних игроков; они обязаны обменяться 1 картой.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'panic_doors_open',
    name: 'Doors Wide Open',
    nameRu: 'Двери нараспашку',
    category: 'panic',
    back: 'panic',
    description: 'Remove all Locked Doors.',
    descriptionRu: 'Убрать все заблокированные двери.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'panic_quarantine_lifted',
    name: 'Quarantine Lifted',
    nameRu: 'Карантин снят',
    category: 'panic',
    back: 'panic',
    description: 'Remove all Quarantine cards.',
    descriptionRu: 'Убрать все карантины.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'panic_musical_chairs',
    name: 'Musical Chairs',
    nameRu: 'Музыкальные стулья',
    category: 'panic',
    back: 'panic',
    description: 'Everyone shifts 1 seat in turn direction simultaneously.',
    descriptionRu: 'Все сдвигаются на 1 место по направлению хода.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'panic_quiet_night',
    name: 'Quiet Night',
    nameRu: 'Тихая ночь',
    category: 'panic',
    back: 'panic',
    description: 'No talking until next turn!',
    descriptionRu: 'Никаких разговоров до следующего хода!',
    copies: 3,
    minPlayers: 4,
  },
];

export function getCardDef(defId: string): CardDef {
  const def = CARD_DEFS.find(d => d.id === defId);
  if (!def) throw new Error(`Unknown card def: ${defId}`);
  return def;
}

export function getCardName(defId: string, lang: 'en' | 'ru'): string {
  const def = getCardDef(defId);
  return lang === 'ru' ? def.nameRu : def.name;
}

export function getCardDescription(defId: string, lang: 'en' | 'ru'): string {
  const def = getCardDef(defId);
  return lang === 'ru' ? def.descriptionRu : def.description;
}
