import type { CardDef } from './types.ts';

// Card definitions with copy counts and minimum player thresholds.
// copiesByPlayerCount: [4p, 5p, 6p, 7p, 8p, 9p, 10p, 11p] — from official card table.
// copies: fallback for player counts outside the table or for cards not in the table.

export const CARD_DEFS: CardDef[] = [
  // ── Infections ────────────────────────────────────────────────────────
  {
    id: 'the_thing',
    name: 'The Thing',
    nameRu: 'Нечто',
    category: 'infection',
    back: 'event',
    description: 'You ARE The Thing. Cannot be discarded or traded.',
    descriptionRu: 'Вы — Нечто. Нельзя сбросить или обменять.',
    copies: 1,
    minPlayers: 4,
  },
  {
    id: 'infected',
    name: 'Infected!',
    nameRu: 'Заражение!',
    category: 'infection',
    back: 'event',
    description: 'Passed by The Thing during trade to infect a player.',
    descriptionRu: 'Передаётся Нечто при обмене для заражения игрока.',
    copies: 8,
    minPlayers: 4,
    copiesByPlayerCount: [8, 8, 10, 12, 13, 15, 17, 20],
  },

  // ── Actions ───────────────────────────────────────────────────────────
  {
    id: 'flamethrower',
    name: 'Flamethrower',
    nameRu: 'Огнемёт',
    category: 'action',
    back: 'event',
    description: 'Eliminate an adjacent player. Blocked by "No Barbecue!"',
    descriptionRu: 'Уничтожить соседнего игрока. Блокируется «Никакого шашлыка!»',
    copies: 5,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 3, 3, 3, 4, 4, 5],
  },
  {
    id: 'analysis',
    name: 'Analysis',
    nameRu: 'Анализ',
    category: 'action',
    back: 'event',
    description: 'Target adjacent player shows you ALL their hand cards.',
    descriptionRu: 'Соседний игрок показывает вам ВСЕ свои карты.',
    copies: 4,
    minPlayers: 4,
    copiesByPlayerCount: [0, 1, 2, 2, 2, 2, 2, 2],
  },
  {
    id: 'axe',
    name: 'Axe',
    nameRu: 'Топор',
    category: 'action',
    back: 'event',
    description: 'Remove a Quarantine card or a Locked Door between you and an adjacent player.',
    descriptionRu: 'Убрать карантин или заблокированную дверь между вами и соседом.',
    copies: 4,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'suspicion',
    name: 'Suspicion',
    nameRu: 'Подозрение',
    category: 'action',
    back: 'event',
    description: 'Take 1 random card from adjacent player, look secretly, return it.',
    descriptionRu: 'Возьмите 1 случайную карту соседа, посмотрите тайно, верните.',
    copies: 6,
    minPlayers: 4,
    copiesByPlayerCount: [4, 4, 4, 5, 6, 7, 8, 8],
  },
  {
    id: 'whisky',
    name: 'Whisky',
    nameRu: 'Виски',
    category: 'action',
    back: 'event',
    description: 'Show ALL your cards to all players.',
    descriptionRu: 'Покажите ВСЕ свои карты всем игрокам.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 2, 2, 3, 3],
  },
  {
    id: 'persistence',
    name: 'Persistence',
    nameRu: 'Упорство',
    category: 'action',
    back: 'event',
    description: 'Draw 3 event cards, keep 1, discard 2. Then play or discard 1 card.',
    descriptionRu: 'Возьмите 3 карты событий, оставьте 1, сбросьте 2. Затем сыграйте или сбросьте ещё 1 карту.',
    copies: 4,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 3, 3, 3, 4, 5, 5],
  },
  {
    id: 'watch_your_back',
    name: 'Watch Your Back!',
    nameRu: 'Оглянись!',
    category: 'action',
    back: 'event',
    description: 'Reverse the turn direction.',
    descriptionRu: 'Изменить направление хода.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'swap_places',
    name: 'Swap Places!',
    nameRu: 'Меняемся местами!',
    category: 'action',
    back: 'event',
    description: 'Swap seats with an adjacent player (not in quarantine, not behind locked door).',
    descriptionRu: 'Поменяться местами с соседом (не на карантине, не за заблокированной дверью).',
    copies: 5,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 2, 3, 3, 4, 4, 5],
  },
  {
    id: 'you_better_run',
    name: "You'd Better Run!",
    nameRu: 'Сматывай удочки!',
    category: 'action',
    back: 'event',
    description: 'Swap seats with ANY non-quarantined player, ignoring locked doors.',
    descriptionRu: 'Поменяться местами с ЛЮБЫМ не на карантине игроком, игнорируя двери.',
    copies: 2,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 2, 3, 3, 4, 4, 5],
  },
  {
    id: 'get_out_of_here',
    name: 'Get Out of Here!',
    nameRu: 'Убирайся прочь!',
    category: 'action',
    back: 'event',
    description: 'Move yourself to any empty position in the circle, ignoring all restrictions.',
    descriptionRu: 'Переместитесь на любое место в круге, игнорируя все ограничения.',
    copies: 1,
    minPlayers: 5,
    copiesByPlayerCount: [0, 1, 1, 1, 1, 1, 1, 1],
  },
  {
    id: 'temptation',
    name: 'Temptation',
    nameRu: 'Соблазн',
    category: 'action',
    back: 'event',
    description: 'Swap 1 card with ANY player (not in quarantine). Both players choose their card. This ends your trade step.',
    descriptionRu: 'Обменяться 1 картой с ЛЮБЫМ игроком (не на карантине). Оба игрока выбирают карту. Обмен завершается.',
    copies: 4,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 3, 4, 5, 5, 6, 7],
  },
  {
    id: 'cant_be_friends',
    name: "Can't We Be Friends?",
    nameRu: 'Давай дружить?',
    category: 'defense',
    back: 'event',
    description: 'Refuse a trade offered to you.',
    descriptionRu: 'Отказаться от предложенного вам обмена.',
    copies: 0,
    minPlayers: 7,
    copiesByPlayerCount: [0, 0, 0, 1, 1, 2, 2, 2],
  },

  // ── Defense ───────────────────────────────────────────────────────────
  {
    id: 'fear',
    name: 'Fear',
    nameRu: 'Страх',
    category: 'defense',
    back: 'event',
    description: 'Refuse trade. Secretly look at the offered card, return it.',
    descriptionRu: 'Отказ от обмена. Тайно посмотрите предложенную карту и верните.',
    copies: 4,
    minPlayers: 4,
    copiesByPlayerCount: [0, 1, 2, 2, 3, 3, 3, 4],
  },
  {
    id: 'no_thanks',
    name: 'No Thanks!',
    nameRu: 'Нет, спасибо!',
    category: 'defense',
    back: 'event',
    description: 'Refuse trade.',
    descriptionRu: 'Отказ от обмена.',
    copies: 4,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 3, 3, 3, 4],
  },
  {
    id: 'miss',
    name: 'Miss!',
    nameRu: 'Мимо!',
    category: 'defense',
    back: 'event',
    description: 'Refuse trade, but the next player in turn order trades instead.',
    descriptionRu: 'Отказ от обмена, но следующий по ходу игрок обменивается вместо вас.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 2, 2, 2, 3],
  },
  {
    id: 'im_fine_here',
    name: "I'm Fine Here",
    nameRu: 'Мне и тут хорошо',
    category: 'defense',
    back: 'event',
    description: 'Cancel "Swap Places!" or "Get Out of Here!"',
    descriptionRu: 'Отменить «Меняемся местами!» или «Убирайся прочь!»',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 2, 2, 2, 3],
  },
  {
    id: 'no_barbecue',
    name: 'No Barbecue!',
    nameRu: 'Никакого шашлыка!',
    category: 'defense',
    back: 'event',
    description: 'Cancel Flamethrower. Stay in the game.',
    descriptionRu: 'Отменить Огнемёт. Остаться в игре.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 2, 2, 2, 3],
  },

  // ── Obstacles ─────────────────────────────────────────────────────────
  {
    id: 'quarantine',
    name: 'Quarantine',
    nameRu: 'Карантин',
    category: 'obstacle',
    back: 'event',
    description: 'Target cannot trade, play events, or be targeted for 3 turns.',
    descriptionRu: 'Цель не может обменивать, играть события или быть целью 3 хода.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [0, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'locked_door',
    name: 'Locked Door',
    nameRu: 'Заколоченная дверь',
    category: 'obstacle',
    back: 'event',
    description: 'Place between you and neighbor. Neither can target each other.',
    descriptionRu: 'Поставить между вами и соседом. Никто не может действовать друг на друга.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 2, 2, 2, 2, 3],
  },
  {
    id: 'rotten_ropes',
    name: 'Rotten Ropes',
    nameRu: 'Старые верёвки',
    category: 'obstacle',
    back: 'event',
    description: 'Place a locked door between two adjacent players of your choice.',
    descriptionRu: 'Поставить заблокированную дверь между двумя соседними игроками по вашему выбору.',
    copies: 0,
    minPlayers: 6,
    copiesByPlayerCount: [0, 0, 1, 1, 1, 2, 2, 2],
  },

  // ── Panic cards ───────────────────────────────────────────────────────
  {
    id: 'panic_1234',
    name: '...Three, Four...',
    nameRu: '...Три, четыре...',
    category: 'panic',
    back: 'panic',
    description: 'Next 3 players swap seats with their neighbor in turn direction.',
    descriptionRu: 'Следующие 3 игрока меняются местами с соседом по направлению хода.',
    copies: 2,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_one_two',
    name: 'One, Two...',
    nameRu: 'Раз, два...',
    category: 'panic',
    back: 'panic',
    description: 'Next 2 players swap seats with their neighbor in turn direction.',
    descriptionRu: 'Следующие 2 игрока меняются местами с соседом по направлению хода.',
    copies: 1,
    minPlayers: 5,
    copiesByPlayerCount: [0, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_party',
    name: 'Is This What You Call a Party?',
    nameRu: 'И это вы называете вечеринкой?',
    category: 'panic',
    back: 'panic',
    description: 'All players pass 1 card to their neighbor in turn direction.',
    descriptionRu: 'Все игроки передают 1 карту соседу по направлению хода.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [0, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_between_us',
    name: 'Just Between Us',
    nameRu: 'Только между нами',
    category: 'panic',
    back: 'panic',
    description: 'Pick two adjacent players; they must trade 1 card each (both choose).',
    descriptionRu: 'Выберите двух соседних игроков; они обязаны обменяться 1 картой каждый (оба выбирают).',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [0, 0, 0, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_chain_reaction',
    name: 'Round and Round',
    nameRu: 'Цепная реакция',
    category: 'panic',
    back: 'panic',
    description: 'All players pass 1 card to their neighbor counter to turn direction.',
    descriptionRu: 'Все игроки передают 1 карту соседу в направлении, противоположном ходу.',
    copies: 1,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_blind_date',
    name: 'Blind Date',
    nameRu: 'Свидание вслепую',
    category: 'panic',
    back: 'panic',
    description: 'Two random adjacent players must swap 1 card.',
    descriptionRu: 'Два случайных соседних игрока обмениваются 1 картой.',
    copies: 1,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_oops',
    name: 'Oops!',
    nameRu: 'Уупс!',
    category: 'panic',
    back: 'panic',
    description: 'The active player randomly swaps one card with a random neighbor.',
    descriptionRu: 'Активный игрок случайно обменивается одной картой со случайным соседом.',
    copies: 0,
    minPlayers: 10,
    copiesByPlayerCount: [0, 0, 0, 0, 0, 0, 1, 1],
  },
  {
    id: 'panic_forgetful',
    name: 'Forgetful',
    nameRu: 'Забывчивость',
    category: 'panic',
    back: 'panic',
    description: 'All players discard 1 random card from their hand.',
    descriptionRu: 'Все игроки сбрасывают 1 случайную карту из руки.',
    copies: 1,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 1, 1, 1],
  },
  {
    id: 'panic_revelations',
    name: 'Revelations',
    nameRu: 'Время признаний',
    category: 'panic',
    back: 'panic',
    description: 'All players must show their entire hand to everyone.',
    descriptionRu: 'Все игроки показывают всю свою руку всем игрокам.',
    copies: 0,
    minPlayers: 8,
    copiesByPlayerCount: [0, 0, 0, 0, 1, 1, 1, 1],
  },
  {
    id: 'panic_doors_open',
    name: 'Doors Wide Open',
    nameRu: 'Двери нараспашку',
    category: 'panic',
    back: 'panic',
    description: 'Remove all Locked Doors.',
    descriptionRu: 'Убрать все заблокированные двери.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'panic_quarantine_lifted',
    name: 'Quarantine Lifted',
    nameRu: 'Карантин снят',
    category: 'panic',
    back: 'panic',
    description: 'Remove all Quarantine cards.',
    descriptionRu: 'Убрать все карантины.',
    copies: 3,
    minPlayers: 4,
  },
  {
    id: 'panic_quiet_night',
    name: 'Quiet Night',
    nameRu: 'Тихая ночь',
    category: 'panic',
    back: 'panic',
    description: 'No talking until next turn!',
    descriptionRu: 'Никаких разговоров до следующего хода!',
    copies: 3,
    minPlayers: 4,
  },
];

export function getCardDef(defId: string): CardDef {
  const def = CARD_DEFS.find(d => d.id === defId);
  if (!def) throw new Error(`Unknown card def: ${defId}`);
  return def;
}

export function getCardName(defId: string, lang: 'en' | 'ru'): string {
  const def = getCardDef(defId);
  return lang === 'ru' ? def.nameRu : def.name;
}

export function getCardDescription(defId: string, lang: 'en' | 'ru'): string {
  const def = getCardDef(defId);
  return lang === 'ru' ? def.descriptionRu : def.description;
}
