import type { CardDef } from './types.ts';

// Card definitions — canonical data for «Нечто из глубокой бездны» / Stay Away.
// copiesByPlayerCount: [4p, 5p, 6p, 7p, 8p, 9p, 10p, 11p]
// Derived from per-copy minPlayers thresholds in the official card table.

export const CARD_DEFS: CardDef[] = [
  // ── Infections ────────────────────────────────────────────────────────
  {
    id: 'the_thing',
    name: 'The Thing',
    nameRu: 'Нечто',
    category: 'infection',
    back: 'event',
    description: 'The Thing role card.',
    descriptionRu: 'Карта роли Нечто.',
    copies: 1,
    minPlayers: 4,
  },
  {
    id: 'infected',
    name: 'Infected!',
    nameRu: 'Заражение!',
    category: 'infection',
    back: 'event',
    description: 'When you receive this card from another player you become infected and must keep it until the end of the game.',
    descriptionRu: 'Получив эту карту от другого игрока, вы становитесь заражённым и обязаны держать её на руке до конца игры.',
    copies: 8,
    minPlayers: 4,
    copiesByPlayerCount: [8, 8, 9, 12, 13, 15, 17, 20],
  },

  // ── Actions ───────────────────────────────────────────────────────────
  {
    id: 'analysis',
    name: 'Analysis',
    nameRu: 'Анализ',
    category: 'action',
    back: 'event',
    description: 'Look at all cards in an adjacent player\'s hand.',
    descriptionRu: 'Посмотрите карты на руке соседнего игрока.',
    copies: 3,
    minPlayers: 5,
    copiesByPlayerCount: [0, 1, 2, 2, 2, 3, 3, 3],
  },
  {
    id: 'flamethrower',
    name: 'Flamethrower',
    nameRu: 'Огнемёт',
    category: 'action',
    back: 'event',
    description: 'An adjacent player is eliminated from the game.',
    descriptionRu: 'Соседний игрок выбывает из игры.',
    copies: 5,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 3, 3, 3, 4, 4, 5],
  },
  {
    id: 'suspicion',
    name: 'Suspicion',
    nameRu: 'Подозрение',
    category: 'action',
    back: 'event',
    description: 'Look at 1 random card from an adjacent player\'s hand.',
    descriptionRu: 'Посмотрите 1 случайную карту на руке соседнего игрока.',
    copies: 9,
    minPlayers: 4,
    copiesByPlayerCount: [5, 5, 5, 6, 7, 8, 9, 9],
  },
  {
    id: 'axe',
    name: 'Axe',
    nameRu: 'Топор',
    category: 'action',
    back: 'event',
    description: 'Discard a Quarantine card played on you or an adjacent player, or a Locked Door between you.',
    descriptionRu: 'Сбросьте сыгранную на вас или на соседнего игрока карту «Карантин» или выложенную между вами карту «Заколоченная дверь».',
    copies: 2,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'persistence',
    name: 'Persistence',
    nameRu: 'Упорство',
    category: 'action',
    back: 'event',
    description: 'Draw 3 event cards, keep 1, discard the other 2. Then play or discard 1 card.',
    descriptionRu: 'Возьмите 3 карты событий, оставьте на руке 1 и сбросьте остальные 2. Затем сыграйте или сбросьте 1 карту.',
    copies: 5,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 3, 3, 3, 4, 5, 5],
  },
  {
    id: 'whisky',
    name: 'Whisky',
    nameRu: 'Виски',
    category: 'action',
    back: 'event',
    description: 'Show all your cards to all other players. Can only be played on yourself.',
    descriptionRu: 'Покажите все свои карты остальным игрокам. Эту карту можно сыграть только на себя.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 2, 2, 3, 3],
  },
  {
    id: 'swap_places',
    name: 'Swap Places!',
    nameRu: 'Меняемся местами!',
    category: 'action',
    back: 'event',
    description: 'Swap seats with an adjacent player (not in quarantine, not behind a locked door).',
    descriptionRu: 'Поменяйтесь местами с соседним игроком, если он не на карантине и не за заколоченной дверью.',
    copies: 5,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 2, 3, 3, 4, 4, 5],
  },
  {
    id: 'watch_your_back',
    name: 'Watch Your Back!',
    nameRu: 'Гляди по сторонам',
    category: 'action',
    back: 'event',
    description: 'Reverse the turn direction and the card exchange direction.',
    descriptionRu: 'Очерёдность хода передаётся в обратную сторону. Меняются порядок хода игроков и направление обмена картами с соседом.',
    copies: 2,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'temptation',
    name: 'Temptation',
    nameRu: 'Соблазн',
    category: 'action',
    back: 'event',
    description: 'Swap 1 card with any player of your choice (not in quarantine). Your turn ends.',
    descriptionRu: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине. Ваш ход заканчивается.',
    copies: 7,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 3, 4, 5, 5, 6, 7],
  },
  {
    id: 'you_better_run',
    name: "You'd Better Run!",
    nameRu: 'Сматывай удочки!',
    category: 'action',
    back: 'event',
    description: 'Swap seats with any player of your choice (not in quarantine). Ignore all locked doors.',
    descriptionRu: 'Поменяйтесь местами с любым игроком по вашему выбору, если он не на карантине. Игнорируйте все заколоченные двери.',
    copies: 5,
    minPlayers: 4,
    copiesByPlayerCount: [2, 2, 2, 3, 3, 4, 4, 5],
  },

  // ── Defense ───────────────────────────────────────────────────────────
  {
    id: 'im_fine_here',
    name: "I'm Fine Here",
    nameRu: 'Мне и здесь неплохо',
    category: 'defense',
    back: 'event',
    description: 'Cancel the effect of "Swap Places!" or "You\'d Better Run!" if you are the target. Draw 1 event card.',
    descriptionRu: 'Отмените эффект карты «Меняемся местами!» или «Сматывай удочки!», если стали её целью. Возьмите 1 карту события.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 2, 2, 2, 3],
  },
  {
    id: 'fear',
    name: 'Fear',
    nameRu: 'Страх',
    category: 'defense',
    back: 'event',
    description: 'Refuse a card exchange and look at the refused card. Draw 1 event card.',
    descriptionRu: 'Откажитесь от обмена картами и посмотрите карту, от которой отказались. Возьмите 1 карту события.',
    copies: 4,
    minPlayers: 5,
    copiesByPlayerCount: [0, 1, 2, 2, 3, 3, 3, 4],
  },
  {
    id: 'no_barbecue',
    name: 'No Barbecue!',
    nameRu: 'Никакого шашлыка!',
    category: 'defense',
    back: 'event',
    description: 'Cancel the effect of "Flamethrower" if you are the target. Draw 1 event card.',
    descriptionRu: 'Отмените эффект карты «Огнемёт», если стали её целью. Возьмите 1 карту события.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 2, 2, 2, 3],
  },
  {
    id: 'miss',
    name: 'Miss!',
    nameRu: 'Мимо!',
    category: 'defense',
    back: 'event',
    description: 'Refuse a card exchange. The next player in turn order trades instead. Draw 1 event card.',
    descriptionRu: 'Откажитесь от обмена картами. Вместо вас картами меняется следующий за вами игрок. Возьмите 1 карту события.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 2, 2, 2, 3],
  },
  {
    id: 'no_thanks',
    name: 'No Thanks!',
    nameRu: 'Нет уж, спасибо!',
    category: 'defense',
    back: 'event',
    description: 'Refuse a card exchange. Draw 1 event card.',
    descriptionRu: 'Откажитесь от обмена картами. Возьмите 1 карту события.',
    copies: 4,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 2, 2, 3, 3, 3, 4],
  },

  // ── Obstacles ─────────────────────────────────────────────────────────
  {
    id: 'locked_door',
    name: 'Locked Door',
    nameRu: 'Заколоченная дверь',
    category: 'obstacle',
    back: 'event',
    description: 'Place between you and an adjacent player. No actions or exchanges can happen between you.',
    descriptionRu: 'Положите эту карту между собой и соседним игроком. Между вами не может совершаться никаких действий и обменов.',
    copies: 3,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 2, 2, 2, 2, 3],
  },
  {
    id: 'quarantine',
    name: 'Quarantine',
    nameRu: 'Карантин',
    category: 'obstacle',
    back: 'event',
    description: 'Play on yourself or an adjacent player. For the next 3 turns, the quarantined player cannot exchange cards, play event cards, or be targeted.',
    descriptionRu: 'Сыграйте эту карту на себя или соседнего игрока. Следующие 3 своих хода игрок на карантине не может меняться картами, играть карты событий или становиться целью таких карт.',
    copies: 2,
    minPlayers: 5,
    copiesByPlayerCount: [0, 1, 1, 1, 1, 2, 2, 2],
  },

  // ── Panic cards ───────────────────────────────────────────────────────
  {
    id: 'panic_chain_reaction',
    name: 'Chain Reaction',
    nameRu: 'Цепная реакция',
    category: 'panic',
    back: 'panic',
    description: 'All players simultaneously pass 1 card to the next player in turn order, ignoring Quarantine and Locked Doors. You cannot refuse with other cards. The Thing may infect by passing an Infected card. Your turn ends.',
    descriptionRu: 'Каждый игрок одновременно с остальными отдаёт 1 карту следующему по порядку хода игроку, игнорируя все сыгранные карты «Карантин» и «Заколоченная дверь». Вы не можете отказаться от получения карты при помощи других карт. Нечто может заразить другого игрока, передав ему карту «Заражение!». Ваш ход заканчивается.',
    copies: 2,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_forgetful',
    name: 'Forgetful',
    nameRu: 'Забывчивость',
    category: 'panic',
    back: 'panic',
    description: 'Discard 3 cards from your hand and draw 3 new event cards, discarding any panic cards drawn.',
    descriptionRu: 'Сбросьте 3 карты с руки и возьмите 3 новые карты событий. Сбрасывайте все попадающиеся карты паники.',
    copies: 1,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 1, 1, 1],
  },
  {
    id: 'get_out_of_here',
    name: 'Get Out of Here!',
    nameRu: 'Убирайся прочь!',
    category: 'panic',
    back: 'panic',
    description: 'Swap seats with any player of your choice (not in quarantine).',
    descriptionRu: 'Поменяйтесь местами с любым игроком по вашему выбору, если он не на карантине.',
    copies: 1,
    minPlayers: 5,
    copiesByPlayerCount: [0, 1, 1, 1, 1, 1, 1, 1],
  },
  {
    id: 'panic_party',
    name: 'Is This What You Call a Party?',
    nameRu: 'И это вы называете вечеринкой?',
    category: 'panic',
    back: 'panic',
    description: 'All Quarantine and Locked Door cards are discarded. Then, starting from you clockwise, all players swap seats in pairs. If odd number, the last player stays.',
    descriptionRu: 'Все сыгранные карты «Карантин» и «Заколоченная дверь» сбрасываются. Затем, начиная с вас и по часовой стрелке, все игроки парами меняются местами. В случае нечётного числа игроков последний игрок остаётся на месте.',
    copies: 2,
    minPlayers: 5,
    copiesByPlayerCount: [0, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_1234',
    name: '...Three, Four...',
    nameRu: '...Три, четыре...',
    category: 'panic',
    back: 'panic',
    description: 'All Locked Door cards are discarded.',
    descriptionRu: 'Все сыгранные карты «Заколоченная дверь» сбрасываются.',
    copies: 2,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_one_two',
    name: 'One, Two...',
    nameRu: 'Раз, два...',
    category: 'panic',
    back: 'panic',
    description: 'Swap seats with the third player to your left or right (your choice). Ignore locked doors. If the target is in quarantine, no swap occurs.',
    descriptionRu: 'Поменяйтесь местами с третьим от вас игроком слева или справа по вашему выбору. Игнорируйте все заколоченные двери. Если игрок на карантине, смены мест не происходит.',
    copies: 2,
    minPlayers: 5,
    copiesByPlayerCount: [0, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_revelations',
    name: 'Revelations',
    nameRu: 'Время признаний',
    category: 'panic',
    back: 'panic',
    description: 'Starting from you in turn order, each player may show or not show all their cards. Revelations end when someone shows an Infected card.',
    descriptionRu: 'Начиная с вас и по порядку хода, каждый игрок либо показывает, либо не показывает все карты на руке остальным игрокам. Время признаний заканчивается, когда кто-то из игроков показывает карту «Заражение!», при этом нет необходимости показывать остальные карты на руке.',
    copies: 1,
    minPlayers: 8,
    copiesByPlayerCount: [0, 0, 0, 0, 1, 1, 1, 1],
  },
  {
    id: 'panic_between_us',
    name: 'Just Between Us',
    nameRu: 'Только между нами...',
    category: 'panic',
    back: 'panic',
    description: 'Show all your hand cards to an adjacent player of your choice.',
    descriptionRu: 'Покажите все карты на руке соседнему игроку по вашему выбору.',
    copies: 2,
    minPlayers: 7,
    copiesByPlayerCount: [0, 0, 0, 1, 1, 2, 2, 2],
  },
  {
    id: 'panic_oops',
    name: 'Oops!',
    nameRu: 'Упс!',
    category: 'panic',
    back: 'panic',
    description: 'Show all your hand cards to all other players.',
    descriptionRu: 'Покажите все свои карты на руке остальным игрокам.',
    copies: 1,
    minPlayers: 10,
    copiesByPlayerCount: [0, 0, 0, 0, 0, 0, 1, 1],
  },
  {
    id: 'panic_blind_date',
    name: 'Blind Date',
    nameRu: 'Свидание вслепую',
    category: 'panic',
    back: 'panic',
    description: 'Swap 1 card from your hand with the top card of the deck, discarding any panic cards drawn. Your turn ends.',
    descriptionRu: 'Поменяйте 1 карту с руки на верхнюю карту общей колоды, сбрасывая все попадающиеся карты паники. Ваш ход заканчивается.',
    copies: 2,
    minPlayers: 4,
    copiesByPlayerCount: [1, 1, 1, 1, 1, 2, 2, 2],
  },
  {
    id: 'cant_be_friends',
    name: "Can't We Be Friends?",
    nameRu: 'Давай дружить?',
    category: 'panic',
    back: 'panic',
    description: 'Swap 1 card with any player of your choice (not in quarantine).',
    descriptionRu: 'Поменяйтесь 1 картой с любым игроком по вашему выбору, если он не на карантине.',
    copies: 2,
    minPlayers: 7,
    copiesByPlayerCount: [0, 0, 0, 1, 1, 2, 2, 2],
  },
  {
    id: 'rotten_ropes',
    name: 'Rotten Ropes',
    nameRu: 'Старые верёвки',
    category: 'panic',
    back: 'panic',
    description: 'All Quarantine cards are discarded.',
    descriptionRu: 'Все сыгранные карты «Карантин» сбрасываются.',
    copies: 2,
    minPlayers: 6,
    copiesByPlayerCount: [0, 0, 1, 1, 1, 2, 2, 2],
  },

  // ── Promo cards ───────────────────────────────────────────────────────
  {
    id: 'lovecraft',
    name: 'H. P. Lovecraft',
    nameRu: 'Г. Ф. Лавкрафт',
    category: 'promo',
    back: 'event',
    description: 'Look at all cards in any chosen player\'s hand.',
    descriptionRu: 'Посмотрите карты на руке любого выбранного игрока.',
    copies: 1,
    minPlayers: 6,
    copiesByPlayerCount: [0, 0, 1, 1, 1, 1, 1, 1],
  },
  {
    id: 'necronomicon',
    name: 'Necronomicon',
    nameRu: 'Некрономикон',
    category: 'promo',
    back: 'event',
    description: 'Any chosen player is eliminated from the game.',
    descriptionRu: 'Любой выбранный игрок выбывает из игры.',
    copies: 1,
    minPlayers: 10,
    copiesByPlayerCount: [0, 0, 0, 0, 0, 0, 1, 1],
  },
];

/** Map defId → card image filename in /cards/ */
const CARD_IMAGES: Record<string, string> = {
  the_thing: 'нечто__p01_r3c3.png',
  infected: 'заражение__p01_r3c2.png',
  analysis: 'анализ__p03_r1c1.png',
  flamethrower: 'огнемет__p03_r2c3.png',
  suspicion: 'подозрение__p04_r2c2.png',
  axe: 'топор__p04_r3c1.png',
  persistence: 'упорство__p05_r1c3.png',
  whisky: 'виски__p05_r2c3.png',
  swap_places: 'меняемся_местами__p06_r2c2.png',
  watch_your_back: 'гляди_по_сторонам__p06_r3c1.png',
  temptation: 'соблазн__p07_r2c1.png',
  you_better_run: 'сматывай_удочки__p07_r3c3.png',
  im_fine_here: 'мне_и_здес_неплохо__p08_r1c2.png',
  fear: 'страх__p08_r2c3.png',
  no_barbecue: 'никакого_шашлыка__p09_r1c1.png',
  miss: 'мимо__p09_r2c1.png',
  no_thanks: 'нет_уж_спасибо__p09_r3c2.png',
  locked_door: 'заколоченная_двер__p10_r2c2.png',
  quarantine: 'карантин__p10_r3c1.png',
  panic_chain_reaction: 'цепная_реакция__p11_r1c1.png',
  panic_forgetful: 'забывчивост__p11_r1c2.png',
  get_out_of_here: 'убирайся_проч__p11_r1c3.png',
  panic_party: 'и_это_вы_называете_вечеринкой__p11_r2c2.png',
  panic_1234: 'три_четыре__p11_r3c1.png',
  panic_one_two: 'раз_два__p11_r3c3.png',
  panic_revelations: 'время_признаний__p12_r1c1.png',
  panic_between_us: 'толко_между_нами__p12_r1c3.png',
  panic_oops: 'упс__p12_r2c1.png',
  panic_blind_date: 'свидание_вслепую__p12_r2c3.png',
  cant_be_friends: 'давай_дружит__p12_r3c2.png',
  rotten_ropes: 'старые_веревки__p13_r1c2.png',
  lovecraft: 'г_ф_лавкрафт__p10_r1c1.png',
  necronomicon: 'некрономикон__p10_r1c2.png',
};

export function getCardImage(defId: string): string | null {
  const file = CARD_IMAGES[defId];
  return file ? `/cards/${encodeURIComponent(file)}` : null;
}

export function getCardDef(defId: string): CardDef {
  const def = CARD_DEFS.find(d => d.id === defId);
  if (!def) throw new Error(`Unknown card def: ${defId}`);
  return def;
}

export function getCardName(defId: string, lang: 'en' | 'ru'): string {
  const def = getCardDef(defId);
  return lang === 'ru' ? def.nameRu : def.name;
}

export function getCardDescription(defId: string, lang: 'en' | 'ru'): string {
  const def = getCardDef(defId);
  return lang === 'ru' ? def.descriptionRu : def.description;
}

/** Calculate total card copies for a given player count */
export function getCardCountForPlayers(defId: string, playerCount: number): number {
  const def = getCardDef(defId);
  if (!def.copiesByPlayerCount) return def.minPlayers <= playerCount ? def.copies : 0;
  const idx = Math.min(Math.max(playerCount - 4, 0), 7);
  return def.copiesByPlayerCount[idx];
}
